name: GCC

on:
  push:
    branches:
      - cata_classic

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: server.Dockerfile
        push: true
        tags: namewasntfound/wowclassic:latest
        cache-from: type=registry,ref=namewasntfound/wowclassic:cache
        cache-to: type=registry,ref=namewasntfound/wowclassic:cache,mode=max
